# Generated by Django 5.2.8 on 2025-11-25 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_detalleproducto_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='inventario.categoria'),
        ),
        migrations.CreateModel(
            name='ProductoEtiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('orden', models.PositiveIntegerField(default=1, help_text='Orden de prioridad de la etiqueta (1 = más importante)')),
                ('etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_etiquetas', to='inventario.etiqueta')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_etiquetas', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Producto-Etiqueta',
                'verbose_name_plural': 'Productos-Etiquetas',
                'ordering': ['orden', 'fecha_asignacion'],
                'unique_together': {('producto', 'etiqueta')},
            },
        ),
    ]
