# Generated by Django 5.2.8 on 2025-11-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_producto_categoria_productoetiqueta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleproducto',
            options={'verbose_name': 'Detalle de Producto', 'verbose_name_plural': 'Detalles de Productos'},
        ),
        migrations.AlterField(
            model_name='detalleproducto',
            name='dimension',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='detalleproducto',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, related_name='productos', to='inventario.etiqueta'),
        ),
        migrations.DeleteModel(
            name='ProductoEtiqueta',
        ),
    ]
